import './globals.css'
import Header from '@/components/shared/header/Header'
import Footer from '@/components/shared/footer/Footer'
import { Inter } from 'next/font/google'
// theme provider
import ThemeProvider from '@/components/shared/themeProvider/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TuanNguyen Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
